apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: {{ .Chart.Name }}
      imagePullPolicy: Always
      env:
        - name: QUARKUS_KUBERNETES_CONFIG_ENABLED
          value: 'true'
        - name: QUARKUS_KUBERNETES_CONFIG_CONFIG_MAPS
          value: {{ .Chart.Name }}-config
        