quarkus:
  http:
    port: 8081
  log:
    console:
      json: false
      format: "%d{HH:mm:ss.SSS} [%t] %-5p %c{36} - %m%n"
    level: WARN
    category:
      "my.project":
        level: INFO
        min-level: TRACE

app:
  my-list:
    - thing1
    - thing2
  config:
    name: Bob
    num: 14

"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc:
        background-validation-interval: 20S
        idle-removal-interval: 30S
        max-size: 10
        min-size: 0
        url: jdbc:postgresql://172.17.0.2:5432/postgres?user=postgres&ApplicationName=my-project&reWriteBatchedInserts=true
      username: postgres

"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create
    datasource:
      db-kind: h2
      jdbc:
        background-validation-interval: 20S
        idle-removal-interval: 30S
        max-size: 10
        min-size: 0
        url: jdbc:h2:mem:default
